spring:
  application:
    name: app-quiz
  datasource:
    url: jdbc:postgresql://localhost:5432/app_quiz
    password: root123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.example.com
    port: 587
    username: xusanov0511@gmail.com
    password: bgiz tuur majv kdir
    protocol: smtp
    smtp.auth: true
    smtp.starttls.enable: true

server:
  port: 9090

